version: "3.9"
services:
  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: >
      osrm-routed --algorithm mld
      --max-table-size 10000
      /data/moscow-latest.osrm