// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/engineers": {
            "get": {
                "description": "ФИО, транспорт, навыки, оборудование, смена и депо каждой бригады; если план уже построен — маршрут и загрузка смены",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Бригады"
                ],
                "summary": "Бригады региона",
                "parameters": [
                    {
                        "type": "string",
                        "description": "регион планирования: east, southeast, southcenter",
                        "name": "region",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.EngineerView"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid region",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "404": {
                        "description": "region not found: no engineers file for region",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "502": {
                        "description": "geocoding service is unavailable | invalid response from external service",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "504": {
                        "description": "geocoding service timed out",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Статус бекенда и доступность ML-сервиса",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Служебное"
                ],
                "summary": "Состояние сервиса",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/plan": {
            "get": {
                "description": "Последний построенный или перепланированный план без пересчёта: маршруты, назначения с полными заявками, неназначенные с адресами и причинами, метрики",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планирование"
                ],
                "summary": "Текущий план региона",
                "parameters": [
                    {
                        "type": "string",
                        "description": "регион планирования: east, southeast, southcenter",
                        "name": "region",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PlanResponse"
                        }
                    },
                    "400": {
                        "description": "invalid region",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "404": {
                        "description": "plan for region not found, call POST /plan first",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Получает CSV файл через multipart/form-data по ключу \"tasks_file\" и выполняет оптимальную и неоптимальную планировку",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планирование"
                ],
                "summary": "Планирование задач по загруженному CSV файлу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "регион планирования: east, southeast, southcenter",
                        "name": "region",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "CSV файл с задачами",
                        "name": "tasks_file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "rules — объяснения только по правилам, без LLM; по умолчанию llm",
                        "name": "explain",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PlanResponse"
                        }
                    },
                    "400": {
                        "description": "invalid region | invalid multipart form | tasks_file is missing in multipart form | invalid or missing columns in tasks CSV | invalid task row in CSV | tasks CSV contains no valid tasks",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "404": {
                        "description": "region not found: no engineers file for region",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "502": {
                        "description": "ml service is unavailable | geocoding service is unavailable | invalid response from external service",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "504": {
                        "description": "ml service timed out | geocoding service timed out",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    }
                }
            }
        },
        "/replan": {
            "post": {
                "description": "Получает новую задачу и текущее время и перепланирует план работ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планирование"
                ],
                "summary": "Перепланирование задач по ранее загруженному CSV файлу с учетом новой задачи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "регион планирования: east, southeast, southcenter",
                        "name": "region",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Данные новой заявки и текущее время",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReplanRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "rules — объяснения только по правилам, без LLM; по умолчанию llm",
                        "name": "explain",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PlanResponse"
                        }
                    },
                    "400": {
                        "description": "invalid region | invalid request data",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "404": {
                        "description": "region not found: no engineers file for region | plan for region not found, call POST /plan first",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "409": {
                        "description": "cached plan references unknown engineer, rebuild it with POST /plan",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "502": {
                        "description": "ml service is unavailable | geocoding service is unavailable | invalid response from external service",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "504": {
                        "description": "ml service timed out | geocoding service timed out",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AssignedTask": {
            "type": "object",
            "properties": {
                "arrival_min": {
                    "type": "integer"
                },
                "end_min": {
                    "type": "integer"
                },
                "engineer_id": {
                    "type": "string"
                },
                "engineer_name": {
                    "type": "string"
                },
                "explanation": {
                    "type": "string"
                },
                "late_min": {
                    "type": "integer"
                },
                "position_in_route": {
                    "type": "integer"
                },
                "priority": {
                    "type": "string"
                },
                "start_min": {
                    "type": "integer"
                },
                "task": {
                    "$ref": "#/definitions/entities.Task"
                },
                "task_id": {
                    "type": "integer"
                }
            }
        },
        "dto.EngineerView": {
            "type": "object",
            "properties": {
                "depot_address": {
                    "type": "string"
                },
                "depot_lat": {
                    "type": "number"
                },
                "depot_lon": {
                    "type": "number"
                },
                "distance_km": {
                    "type": "number"
                },
                "equipment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Equipment"
                    }
                },
                "id": {
                    "type": "string"
                },
                "load_percent": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "service_time_min": {
                    "type": "integer"
                },
                "shift_end": {
                    "type": "integer"
                },
                "shift_start": {
                    "type": "integer"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Skill"
                    }
                },
                "task_count": {
                    "type": "integer"
                },
                "task_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "transport": {
                    "type": "string"
                },
                "travel_time_min": {
                    "type": "integer"
                }
            }
        },
        "dto.HealthResponse": {
            "type": "object",
            "properties": {
                "ml": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.Metrics": {
            "type": "object",
            "properties": {
                "assigned": {
                    "type": "integer"
                },
                "assigned_rate": {
                    "type": "number"
                },
                "engineers_used": {
                    "type": "integer"
                },
                "late_count": {
                    "type": "integer"
                },
                "load_max": {
                    "type": "integer"
                },
                "load_mean": {
                    "type": "number"
                },
                "load_min": {
                    "type": "integer"
                },
                "load_std": {
                    "type": "number"
                },
                "overtime_min": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_distance_km": {
                    "type": "number"
                },
                "total_late_min": {
                    "type": "integer"
                },
                "total_tasks": {
                    "type": "integer"
                },
                "total_time_min": {
                    "type": "integer"
                },
                "total_travel_min": {
                    "type": "integer"
                },
                "unassigned": {
                    "type": "integer"
                }
            }
        },
        "dto.PlanChange": {
            "type": "object",
            "properties": {
                "delta_min": {
                    "type": "integer"
                },
                "from_engineer_id": {
                    "type": "string"
                },
                "new_start_min": {
                    "type": "integer"
                },
                "old_start_min": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "to_engineer_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.PlanResponse": {
            "type": "object",
            "properties": {
                "assigned": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AssignedTask"
                    }
                },
                "baseline_metrics": {
                    "$ref": "#/definitions/dto.Metrics"
                },
                "changes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PlanChange"
                    }
                },
                "ml_metrics": {
                    "$ref": "#/definitions/dto.Metrics"
                },
                "routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Route"
                    }
                },
                "unassigned": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UnassignedTask"
                    }
                }
            }
        },
        "dto.ReplanRequest": {
            "type": "object",
            "properties": {
                "current_time_min": {
                    "type": "integer"
                },
                "new_task": {
                    "$ref": "#/definitions/entities.Task"
                }
            }
        },
        "dto.Route": {
            "type": "object",
            "properties": {
                "distance_km": {
                    "type": "number"
                },
                "engineer_id": {
                    "type": "string"
                },
                "engineer_name": {
                    "type": "string"
                },
                "service_time_min": {
                    "type": "integer"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Task"
                    }
                },
                "time_min": {
                    "type": "integer"
                },
                "transport": {
                    "type": "string"
                },
                "travel_time_min": {
                    "type": "integer"
                }
            }
        },
        "dto.UnassignedTask": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "task": {
                    "$ref": "#/definitions/entities.Task"
                },
                "task_id": {
                    "type": "integer"
                }
            }
        },
        "entities.Equipment": {
            "type": "string",
            "enum": [
                "router",
                "tv_box",
                "cable_kit",
                "optics_kit",
                "gigabit_kit"
            ],
            "x-enum-varnames": [
                "RouterEq",
                "TvBoxEq",
                "CableKitEq",
                "OpticsKitEq",
                "GigabitKitEq"
            ]
        },
        "entities.Skill": {
            "type": "string",
            "enum": [
                "basic",
                "fmc",
                "fttb",
                "gigabit",
                "emergency"
            ],
            "x-enum-varnames": [
                "BasicSkill",
                "FMCSkill",
                "FTTBSkill",
                "GigabitSkill",
                "EmergencySkill"
            ]
        },
        "entities.Task": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "priority": {
                    "type": "string"
                },
                "required_equipment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Equipment"
                    }
                },
                "required_skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Skill"
                    }
                },
                "service_time": {
                    "type": "integer"
                },
                "tw_end": {
                    "type": "integer"
                },
                "tw_start": {
                    "type": "integer"
                },
                "type_bk": {
                    "type": "string"
                },
                "type_hd": {
                    "type": "string"
                }
            }
        },
        "errors.HttpErrorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Beeline Plan Tasks",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
