// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/plan": {
            "post": {
                "description": "Получает CSV файл через multipart/form-data по ключу \"tasks_file\" и выполняет оптимальную и неоптимальную планировку",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планирование"
                ],
                "summary": "Планирование задач по загруженному CSV файлу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "регион планирования: east, southeast, southcenter",
                        "name": "region",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "CSV файл с задачами",
                        "name": "tasks_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PlanResponse"
                        }
                    },
                    "400": {
                        "description": "required tasks file is missing in multipart form",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "404": {
                        "description": "address not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "502": {
                        "description": "external service is unavailable",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    }
                }
            }
        },
        "/replan": {
            "post": {
                "description": "Получает новую задачу и текущее время и перепланирует план работ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планирование"
                ],
                "summary": "Перепланирование задач по ранее загруженному CSV файлу с учетом новой задачи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "регион планирования: east, southeast, southcenter",
                        "name": "region",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Данные новой заявки и текущее время",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReplanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PlanResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request data",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "404": {
                        "description": "address not found",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    },
                    "502": {
                        "description": "external service is unavailable",
                        "schema": {
                            "$ref": "#/definitions/errors.HttpErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AssignedTask": {
            "type": "object",
            "properties": {
                "arrival_min": {
                    "type": "integer"
                },
                "end_min": {
                    "type": "integer"
                },
                "engineer_id": {
                    "type": "string"
                },
                "engineer_name": {
                    "type": "string"
                },
                "explanation": {
                    "type": "string"
                },
                "late_min": {
                    "type": "integer"
                },
                "position_in_route": {
                    "type": "integer"
                },
                "priority": {
                    "type": "string"
                },
                "start_min": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "tw_end": {
                    "type": "integer"
                },
                "tw_start": {
                    "type": "integer"
                }
            }
        },
        "dto.Metrics": {
            "type": "object",
            "properties": {
                "assigned": {
                    "type": "integer"
                },
                "assigned_rate": {
                    "type": "number"
                },
                "engineers_used": {
                    "type": "integer"
                },
                "late_count": {
                    "type": "integer"
                },
                "load_max": {
                    "type": "integer"
                },
                "load_mean": {
                    "type": "number"
                },
                "load_min": {
                    "type": "integer"
                },
                "load_std": {
                    "type": "number"
                },
                "overtime_min": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_distance_km": {
                    "type": "number"
                },
                "total_late_min": {
                    "type": "integer"
                },
                "total_tasks": {
                    "type": "integer"
                },
                "unassigned": {
                    "type": "integer"
                }
            }
        },
        "dto.PlanResponse": {
            "type": "object",
            "properties": {
                "assigned": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AssignedTask"
                    }
                },
                "baseline_metrics": {
                    "$ref": "#/definitions/dto.Metrics"
                },
                "ml_metrics": {
                    "$ref": "#/definitions/dto.Metrics"
                },
                "routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Route"
                    }
                },
                "unassigned": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UnassignedTask"
                    }
                }
            }
        },
        "dto.ReplanRequest": {
            "type": "object",
            "properties": {
                "current_time_min": {
                    "type": "integer"
                },
                "new_task": {
                    "$ref": "#/definitions/entities.Task"
                }
            }
        },
        "dto.Route": {
            "type": "object",
            "properties": {
                "distance_km": {
                    "type": "number"
                },
                "engineer_id": {
                    "type": "string"
                },
                "engineer_name": {
                    "type": "string"
                },
                "service_time_min": {
                    "type": "integer"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Task"
                    }
                },
                "time_min": {
                    "type": "integer"
                },
                "transport": {
                    "type": "string"
                },
                "travel_time_min": {
                    "type": "integer"
                }
            }
        },
        "dto.UnassignedTask": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "task_id": {
                    "type": "integer"
                }
            }
        },
        "entities.Equipment": {
            "type": "string",
            "enum": [
                "router",
                "tv_box",
                "cable_kit",
                "optics_kit",
                "gigabit_kit"
            ],
            "x-enum-varnames": [
                "RouterEq",
                "TvBoxEq",
                "CableKitEq",
                "OpticsKitEq",
                "GigabitKitEq"
            ]
        },
        "entities.Skill": {
            "type": "string",
            "enum": [
                "basic",
                "fmc",
                "fttb",
                "gigabit",
                "emergency"
            ],
            "x-enum-varnames": [
                "BasicSkill",
                "FMCSkill",
                "FTTBSkill",
                "GigabitSkill",
                "EmergencySkill"
            ]
        },
        "entities.Task": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "priority": {
                    "type": "string"
                },
                "required_equipment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Equipment"
                    }
                },
                "required_skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Skill"
                    }
                },
                "service_time": {
                    "type": "integer"
                },
                "tw_end": {
                    "type": "integer"
                },
                "tw_start": {
                    "type": "integer"
                },
                "type_bk": {
                    "type": "string"
                },
                "type_hd": {
                    "type": "string"
                }
            }
        },
        "errors.HttpErrorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Beeline Plan Tasks",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
